# Generated by Django 2.0.3 on 2019-07-22 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('confirmed', models.IntegerField(choices=[(1, 'zapytanie wysłane'), (2, 'potwierdzona')])),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=200)),
                ('car_type', models.IntegerField(choices=[(1, 'camper'), (2, 'dostawczy'), (3, 'osobowy')])),
                ('description', models.TextField()),
                ('sits', models.SmallIntegerField()),
                ('engine', models.CharField(max_length=100)),
                ('deposit', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=280)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PriceCarDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(choices=[(1, 'niski 1.01-24.04'), (2, 'wysoki 25.04-8.05'), (3, 'średni 9.05-5.06'), (4, 'wysoki 6.06-31.08'), (5, 'średni 1.09-30.09'), (6, 'niski 1.10-31.12'), (7, 'bez znaczenia')])),
                ('km_limit', models.IntegerField(choices=[(1, '200km dziennie'), (2, '400 km dziennie'), (3, 'bez limitu')])),
                ('price_per_day', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation_app.Cars')),
            ],
        ),
        migrations.AddField(
            model_name='carreservation',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation_app.Cars'),
        ),
        migrations.AddField(
            model_name='carreservation',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation_app.Message'),
        ),
        migrations.AddField(
            model_name='carreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
